name: 'changed files'

on:
  push:
    branches:
      - main
    paths:
      - change-test/**
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - change-test/**

jobs:
  changed_files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          files: 'change-test/**'
          dir_names: "true"
      - name: Test changes
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$dir was changed"
          done

