name: checks

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed

concurrency:
  group: checks-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo ${{ github.head_ref }}
