name: checks

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed

concurrency:
  group: checks-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: juliangruber/find-pull-request-action@v1
        id: find_pr
        with:
          branch: ${{ github.head_ref }}
      - name: debug
        run: |
          echo "number=${{ steps.find_pr.outputs.number }}"
          echo "head_sha=${{ steps.find_pr.outputs.head-sha }}"
      - name: Create checks
        run: |
          gh api /repos/${{ github.repository }}/commits/${{ steps.find_pr.outputs.head-sha }}/check-runs > ${{ runner.temp }}/check-run
          non_completed_count=$(cat ${{ runner.temp }}/check-run | jq -r '[.check_runs[] | select(.name != "pr_check" and .status != "completed")] | length')
          failure_count=$(cat ${{ runner.temp }}/check-run | jq -r '[.check_runs[] | select(.name != "pr_check" and .status == "completed" and .conclusion == "failure")] | length')

          echo "non_completed_count=$non_completed_count"
          echo "failure_count=$failure_count"

          conclusion="success"
          if [ $non_completed_count -gt 0 ]; then
            conclusion="queued"
          elif [ $failure_count -gt 0 ]; then
            conclusion="failure"
          fi

          gh api /repos/${{ github.repository }}/check-runs -f name=pr_check -f head_sha=${{ steps.find_pr.outputs.head-sha }} -f status=completed -f conclusion=$conclusion

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

