name: "issue_comment test"
on:
  issue_comment:
    types: [created]
jobs:
  setup:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v2
        with:
          command: tfmigrate
          reaction-type: "eyes"
      - run: |
          ls -l .github/workflows/
