name: "issue_comment test"
on:
  issue_comment:
    types: [created]
permissions:
  contents: read

jobs:
  setup:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@bf51f8f5f4ea3d58abc7eca58f77104182b23e88 # v2.0.0
        with:
          command: test
          reaction-type: "eyes"
      - run: |
          ls -l .github/workflows/
