name: sha
on:
  workflow_dispatch:

jobs:
  sha:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: "${{ steps.short-sha.outputs.result }}"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - id: short-sha
        name: Get short SHA
        run: echo "result=$(git rev-parse HEAD | cut -c 1-8)" >> "$GITHUB_OUTPUT"

  out:
    needs:
      - sha
    runs-on: ubuntu-latest
    steps:
      - name: 'debug'
        run: |
          echo "${{ needs.output_short_sha.outputs.result }}"
